NAME = account
SRC = Account.cpp tests.cpp
FLAG = -Wall -Wextra -Werror -std=c++98

$(NAME):
	g++ $(FLAG) $(SRC) -o $(NAME)

clean:
		rm -f $(NAME)

fclean: clean

all: $(NAME)

re: fclean all