SRC = megaphone.cpp
FLAGS = -Wall -Wextra -Werror -std=c++98
NAME = megaphone

$(NAME):
	g++ $(FLAGS) $(SRC) -o $(NAME)
clean:
		rm -f $(NAME)

fclean: clean

all: $(NAME)

re: fclean all