NAME = pipex

SRC = pipex.c ft_strjoin.c ft_split.c ft_strlen.c ft_strncmp.c

FLAG = -Wall -Wextra -Werror

$(NAME):
		gcc $(FLAG) $(SRC) -o $(NAME)

clean:
		rm -f $(NAME)

fclean: clean

all: $(NAME)

re: fclean all